import type { CoachingActionDefinition } from "./types";

const verifiedAt = "2026-07-20";
const reviewAfter = "2027-07-20";

function action(
  definition: CoachingActionDefinition,
): CoachingActionDefinition {
  return Object.freeze({
    ...definition,
    triggerKeys: Object.freeze([...definition.triggerKeys]),
    blockerKeys: Object.freeze([...definition.blockerKeys]),
    requiredEvidence: Object.freeze([...definition.requiredEvidence]),
    followUpQuestions: Object.freeze([...definition.followUpQuestions]),
    steps: Object.freeze([...definition.steps]),
  }) as unknown as CoachingActionDefinition;
}

export const coachingActions: readonly CoachingActionDefinition[] =
  Object.freeze([
    action({
      key: "verify_search_visibility",
      intent: "discovery",
      title: "우리 가게가 실제로 노출되는 검색어 확인하기",
      triggerKeys: ["not_visible", "search_visibility"],
      blockerKeys: [],
      requiredEvidence: ["검색 결과", "가게 정보"],
      followUpQuestions: [],
      reasonTemplate: "노출 여부를 먼저 확인해야 다음 개선을 고를 수 있습니다.",
      steps: [
        "고객이 찾을 만한 검색어 3개를 적습니다.",
        "로그아웃 상태에서 각 검색어의 결과를 기록합니다.",
      ],
      metric: "검색어별 노출 여부",
      avoid: "순위나 노출을 보장한다고 말하지 마세요.",
      evidenceLevel: "official",
      verifiedAt,
      reviewAfter,
      version: 1,
    }),
    action({
      key: "rewrite_search_intent_profile",
      intent: "discovery",
      title: "방문 목적이 보이는 소개 문장으로 바꾸기",
      triggerKeys: ["not_visible", "search_intent"],
      blockerKeys: ["search_visibility_unknown"],
      requiredEvidence: ["현재 소개 문장", "고객의 방문 목적"],
      followUpQuestions: ["visit_purpose"],
      reasonTemplate:
        "검색한 사람이 왜 이곳에 와야 하는지 소개에서 바로 알 수 있어야 합니다.",
      steps: [
        "고객이 찾는 상황을 한 문장으로 적습니다.",
        "소개 첫 문장을 그 상황과 대표 메뉴가 보이게 고칩니다.",
      ],
      metric: "수정 전후 상세 진입 수",
      avoid: "검색 순위 상승을 보장하지 마세요.",
      evidenceLevel: "principle",
      verifiedAt,
      version: 1,
    }),
    action({
      key: "audit_cover_photo",
      intent: "selection",
      title: "대표사진 한 장으로 선택 이유 보여주기",
      triggerKeys: ["visible_no_visit", "cover_photo"],
      blockerKeys: [],
      requiredEvidence: ["현재 대표사진"],
      followUpQuestions: [],
      reasonTemplate:
        "대표사진은 손님이 가게를 더 살펴볼지 결정하는 첫 단서입니다.",
      steps: [
        "대표 메뉴 또는 매장 강점이 한눈에 보이는 사진을 고릅니다.",
        "작은 화면에서도 무엇을 파는지 보이는지 확인합니다.",
      ],
      metric: "대표사진 변경 후 상세 진입률",
      avoid: "과장된 보정이나 실제와 다른 사진을 쓰지 마세요.",
      evidenceLevel: "principle",
      verifiedAt,
      version: 1,
    }),
    action({
      key: "clarify_signature_menu",
      intent: "selection",
      title: "대표 메뉴·가격·주문 조합 정리하기",
      triggerKeys: ["visible_no_visit", "menu_confusion"],
      blockerKeys: [],
      requiredEvidence: ["메뉴판", "대표 메뉴 가격"],
      followUpQuestions: [],
      reasonTemplate:
        "무엇을 얼마에 어떻게 주문하는지 빨리 이해되면 선택 부담이 줄어듭니다.",
      steps: [
        "처음 온 손님에게 권할 대표 메뉴를 하나 고릅니다.",
        "가격과 인원·주문 조합을 한 줄로 정리합니다.",
      ],
      metric: "대표 메뉴 조회 또는 주문 비중",
      avoid: "없는 할인이나 혜택을 덧붙이지 마세요.",
      evidenceLevel: "principle",
      verifiedAt,
      version: 1,
    }),
    action({
      key: "define_selection_reason",
      intent: "selection",
      title: "우리 가게를 선택할 이유 두 가지 정하기",
      triggerKeys: ["visible_no_visit", "selection_reason"],
      blockerKeys: [],
      requiredEvidence: ["고객 후기", "매장 강점"],
      followUpQuestions: ["customer_choice_reason"],
      reasonTemplate:
        "손님이 비교할 때 기억할 이유가 있어야 선택으로 이어질 수 있습니다.",
      steps: [
        "고객이 자주 언급한 강점 두 가지를 고릅니다.",
        "사진·소개·메뉴 설명에 같은 표현으로 반영합니다.",
      ],
      metric: "선택 이유를 언급한 고객 수",
      avoid: "경쟁 가게를 깎아내리지 마세요.",
      evidenceLevel: "hypothesis",
      verifiedAt,
      version: 1,
    }),
    action({
      key: "complete_visit_information",
      intent: "confidence",
      title: "영업시간·주소·예약·대기 정보를 완성하기",
      triggerKeys: ["visible_no_visit", "visit_information"],
      blockerKeys: [],
      requiredEvidence: ["영업시간", "주소", "예약 또는 대기 정보"],
      followUpQuestions: [],
      reasonTemplate:
        "방문 전 기본 정보가 비어 있으면 손님은 확인을 미루거나 포기할 수 있습니다.",
      steps: [
        "영업시간과 휴무일을 실제 운영 기준으로 확인합니다.",
        "주소와 예약·대기 방법을 한곳에 정리합니다.",
      ],
      metric: "같은 문의 건수 변화",
      avoid: "확인하지 않은 운영 정보를 게시하지 마세요.",
      evidenceLevel: "official",
      verifiedAt,
      reviewAfter,
      version: 1,
    }),
    action({
      key: "classify_customer_questions",
      intent: "confidence",
      title: "반복되는 고객 질문과 불만 분류하기",
      triggerKeys: ["visible_no_visit", "customer_questions"],
      blockerKeys: [],
      requiredEvidence: ["문의 또는 후기"],
      followUpQuestions: [],
      reasonTemplate: "반복 질문을 묶으면 먼저 고칠 정보가 보입니다.",
      steps: [
        "최근 문의와 후기에서 질문·불만을 모읍니다.",
        "같은 내용끼리 묶어 가장 많은 유형을 표시합니다.",
      ],
      metric: "상위 질문 유형별 건수",
      avoid: "한두 건의 의견을 전체 고객의 생각으로 단정하지 마세요.",
      evidenceLevel: "principle",
      verifiedAt,
      version: 1,
    }),
    action({
      key: "rewrite_detail_answers",
      intent: "confidence",
      title: "상세 설명을 고객 질문의 답으로 바꾸기",
      triggerKeys: ["visible_no_visit", "customer_questions"],
      blockerKeys: ["questions_unclassified"],
      requiredEvidence: ["상위 고객 질문", "현재 상세 설명"],
      followUpQuestions: [],
      reasonTemplate:
        "자주 묻는 질문의 답을 미리 보여주면 방문 전 망설임을 줄일 수 있습니다.",
      steps: [
        "가장 많은 질문 하나를 고릅니다.",
        "상세 설명 첫 부분에 짧고 정확한 답을 추가합니다.",
      ],
      metric: "문의 후 방문 전환 수",
      avoid: "답할 수 없는 사항을 확정적으로 약속하지 마세요.",
      evidenceLevel: "hypothesis",
      verifiedAt,
      version: 1,
    }),
    action({
      key: "track_ad_to_visit_path",
      intent: "visit",
      title: "광고부터 실제 방문까지 경로 기록하기",
      triggerKeys: ["ads_no_customers", "ad_attribution"],
      blockerKeys: ["advertising_inactive"],
      requiredEvidence: ["광고 유입", "실제 방문 기록"],
      followUpQuestions: ["ad_conversion_known"],
      reasonTemplate:
        "광고비를 바꾸기 전에 광고 유입이 실제 방문으로 이어지는지 측정해야 합니다.",
      steps: [
        "광고별로 구분 가능한 문의·예약 경로를 하나 정합니다.",
        "7일 동안 유입과 실제 방문을 같은 표에 기록합니다.",
      ],
      metric: "광고 유입 대비 실제 방문 수",
      avoid: "전환 기록 없이 광고 예산을 늘리거나 줄이지 마세요.",
      evidenceLevel: "principle",
      verifiedAt,
      version: 1,
    }),
    action({
      key: "find_visit_dropoff",
      intent: "visit",
      title: "클릭·전화·예약·방문 중 이탈 지점 찾기",
      triggerKeys: ["ads_no_customers", "visible_no_visit", "visit_dropoff"],
      blockerKeys: ["visit_path_unmeasured"],
      requiredEvidence: ["클릭", "전화 또는 예약", "방문 기록"],
      followUpQuestions: ["visit_path_stage"],
      reasonTemplate:
        "어느 단계에서 멈추는지 알아야 한 번에 한 문제를 고칠 수 있습니다.",
      steps: [
        "클릭·전화·예약·방문 수를 같은 기간으로 적습니다.",
        "가장 크게 줄어든 단계 하나만 고릅니다.",
      ],
      metric: "단계별 전환율",
      avoid: "데이터가 없는 단계를 추정으로 채우지 마세요.",
      evidenceLevel: "principle",
      verifiedAt,
      version: 1,
    }),
    action({
      key: "identify_return_reason",
      intent: "returning",
      title: "첫 방문에서 다시 올 이유 확인하기",
      triggerKeys: ["low_returning", "return_reason"],
      blockerKeys: [],
      requiredEvidence: ["첫 방문 고객 의견"],
      followUpQuestions: ["return_reason_known"],
      reasonTemplate:
        "재방문은 먼저 손님이 다시 올 이유를 확인하는 것에서 시작합니다.",
      steps: [
        "첫 방문 고객에게 짧은 선택형 질문을 준비합니다.",
        "답변을 맛·편의·가격·서비스로 분류합니다.",
      ],
      metric: "재방문 이유 응답 수",
      avoid: "동의 없이 연락처나 후기를 요구하지 마세요.",
      evidenceLevel: "hypothesis",
      verifiedAt,
      version: 1,
    }),
    action({
      key: "offer_consent_based_return",
      intent: "returning",
      title: "동의한 고객에게 재방문 이유 안내하기",
      triggerKeys: ["low_returning", "return_offer"],
      blockerKeys: ["customer_consent_missing"],
      requiredEvidence: ["고객 연락 동의", "재방문 이유"],
      followUpQuestions: ["customer_consent"],
      reasonTemplate:
        "연락 동의를 확인한 고객에게만 재방문할 이유를 안내할 수 있습니다.",
      steps: [
        "연락 동의 여부와 목적을 확인합니다.",
        "동의한 고객에게만 실제 제공 가능한 이유를 한 번 안내합니다.",
      ],
      metric: "동의 고객의 재방문 수",
      avoid: "동의하지 않은 고객에게 메시지를 보내지 마세요.",
      evidenceLevel: "principle",
      verifiedAt,
      version: 1,
    }),
    action({
      key: "offer_natural_add_on",
      intent: "profit",
      title: "대표 메뉴 옆에 자연스러운 추가 주문 제안하기",
      triggerKeys: ["low_average_order_value", "add_on"],
      blockerKeys: ["menu_change_unavailable"],
      requiredEvidence: ["대표 메뉴", "추가 메뉴"],
      followUpQuestions: [],
      reasonTemplate:
        "손님에게 어울리는 선택지를 명확히 보여주면 주문 조합을 검토할 수 있습니다.",
      steps: [
        "대표 메뉴와 잘 맞는 추가 메뉴 하나를 고릅니다.",
        "주문 시점에 선택 이유와 가격을 짧게 안내합니다.",
      ],
      metric: "추가 주문 선택률과 객단가",
      avoid: "필요하지 않은 메뉴를 강요하지 마세요.",
      evidenceLevel: "hypothesis",
      verifiedAt,
      version: 1,
    }),
    action({
      key: "separate_peak_operations",
      intent: "profit",
      title: "붐비는 시간과 한산한 시간 운영을 나누기",
      triggerKeys: ["low_average_order_value", "capacity"],
      blockerKeys: [],
      requiredEvidence: ["시간대별 주문", "시간대별 매출"],
      followUpQuestions: ["peak_hours_known"],
      reasonTemplate:
        "시간대별 운영 차이를 보면 손님이 몰릴 때의 병목을 줄일 수 있습니다.",
      steps: [
        "한 주 동안 시간대별 주문 수와 매출을 기록합니다.",
        "가장 붐비는 시간대의 한 가지 작업을 단순화합니다.",
      ],
      metric: "시간대별 회전율과 매출",
      avoid: "인력이나 영업시간을 근거 없이 줄이지 마세요.",
      evidenceLevel: "principle",
      verifiedAt,
      version: 1,
    }),
    action({
      key: "audit_capacity_channels",
      intent: "profit",
      title: "좌석·포장·배달 구조로 수용량 점검하기",
      triggerKeys: ["low_average_order_value", "capacity", "ads_no_customers"],
      blockerKeys: [],
      requiredEvidence: ["좌석", "포장", "배달 주문"],
      followUpQuestions: ["order_channel_capacity"],
      reasonTemplate:
        "수용량을 넘으면 더 많은 유입보다 주문 처리 구조를 먼저 점검해야 합니다.",
      steps: [
        "좌석·포장·배달별 주문과 처리 시간을 기록합니다.",
        "가장 오래 걸리는 채널의 병목 하나를 고릅니다.",
      ],
      metric: "채널별 주문 수와 처리 시간",
      avoid: "수용량 확인 전 신규 광고를 확대하지 마세요.",
      evidenceLevel: "hypothesis",
      verifiedAt,
      version: 1,
    }),
  ]);
